-- 코드를 입력하세요
SELECT DISTINCT s1.USER_ID, s1.PRODUCT_ID

FROM ONLINE_SALE s1 JOIN 
ONLINE_SALE s2 
ON 
s1.USER_ID = s2.USER_ID

WHERE s1.PRODUCT_ID = s2.PRODUCT_ID AND
s1.ONLINE_SALE_ID != s2.ONLINE_SALE_ID

ORDER BY s1.USER_ID , s1.PRODUCT_ID DESC;