-- 코드를 작성해주세요
SELECT T.ID, 
CASE 
    WHEN T.RANKING = 1 THEN 'CRITICAL'      
    WHEN T.RANKING = 2 THEN 'HIGH'
    WHEN T.RANKING = 3 THEN 'MEDIUM'
    ELSE 'LOW'
    END AS COLONY_NAME
FROM 
(SELECT ID, NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) as RANKING
FROM ECOLI_DATA ) T
ORDER BY T.ID;