-- 코드를 작성해주세요

-- 연도별 가장 큰 걸 찾아야한다
WITH BIG AS (
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) as MAX
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
)

SELECT b.YEAR, 
    (b.MAX - e.SIZE_OF_COLONY) AS YEAR_DEV,
    e.ID
FROM ECOLI_DATA e
JOIN BIG b ON b.YEAR = YEAR(e.DIFFERENTIATION_DATE) 
-- 비교를 할 때 함수(별칭.컬럼) 순서로 진행한다
ORDER BY b.YEAR , YEAR_DEV;
