-- 코드를 입력하세요
SELECT g.TITLE, g.BOARD_ID, r.REPLY_ID, r.WRITER_ID, r.CONTENTS,
TO_CHAR(r.CREATED_DATE, 'YYYY-MM-DD') as CREATED_DATE
FROM USED_GOODS_BOARD g INNER JOIN USED_GOODS_REPLY r ON
g.BOARD_ID = r.BOARD_ID

WHERE TO_CHAR(g.CREATED_DATE, 'YYYY-MM') = '2022-10'
ORDER BY r.CREATED_DATE , g.TITLE;